<div class="paragraph">
<p>It is very easy to write incomplete assertions when using some test frameworks. This rule enforces complete Chai assertions in the following cases:</p>
</div>
<div class="ulist">
<ul>
<li>
<p>when <code>assert.fail</code>, <code>expect.fail</code> or <code>should.fail</code> are present but not called.</p>
</li>
<li>
<p>when an <code>expect(...)</code> or <code>should</code> assertion is not followed by an assertion method, such as <code>equal</code>.</p>
</li>
<li>
<p>when an <code>expect</code> or <code>should</code> assertion ends with a <a href="https://www.chaijs.com/api/bdd/#method_language-chains">chainable getters</a>, such as <code>.that</code>, or a modifier, such as <code>.deep</code>.</p>
</li>
<li>
<p>when an <code>expect</code> or <code>should</code> assertion function, such as <code>.throw</code>, is not called.</p>
</li>
</ul>
</div>
<div class="paragraph">
<p>In such cases, what is intended to be a test doesn&#8217;t actually verify anything</p>
</div>
<div class="sect1">
<h2 id="_noncompliant_code_example">Noncompliant Code Example</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>const assert = require('chai').assert;
const expect = require('chai').expect;

describe("incomplete assertions", function() {
    const value = 42;

    it("uses chai 'assert'", function() {
        assert.fail;  // Noncompliant
    });

    it("uses chai 'expect'", function() {
        expect(1 == 1);  // Noncompliant
        expect(value.toString).to.throw;  // Noncompliant
    });
});</pre>
</div>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_compliant_solution">Compliant Solution</h2>
<div class="sectionbody">
<div class="listingblock">
<div class="content">
<pre>const assert = require('chai').assert;
const expect = require('chai').expect;

describe("incomplete assertions", function() {
    const value = 42;

    it("uses chai 'assert'", function() {
        assert.fail();
    });

    it("uses chai 'expect'", function() {
        expect(1).to.equal(1);
        expect(value.toString).throw(TypeError);
    });
});</pre>
</div>
</div>
<hr/>
</div>
</div>
<div class="sect1">
<h2 id="_implementation_specification">Implementation Specification</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_message">Message</h3>
<div class="paragraph">
<p>Complete the assertion.</p>
</div>
</div>
<div class="sect2">
<h3 id="_highlighting">Highlighting</h3>
<div class="paragraph">
<p>If the assert chain does not end with an assertion function:</p>
</div>
<div class="ulist">
<ul>
<li>
<p>Primary: on the last element of the chain
message: 'Complete this assertion; "X" does not assert anything.'</p>
</li>
</ul>
</div>
<div class="paragraph">
<p>If the assert chain ends with an assertion function which is not called:</p>
</div>
<div class="ulist">
<ul>
<li>
<p>Primary: on the last assertion function.
message: 'Call this assertion function.'</p>
</li>
</ul>
</div>
<hr/>
</div>
</div>
</div>
<div class="sect1">
<h2 id="_comments_and_links">Comments And Links</h2>
<div class="sectionbody">
<div class="paragraph">
<p>(visible only on this page)</p>
</div>
<div class="sect2">
<h3 id="_is_duplicated_by_s2858">is duplicated by: S2858</h3>

</div>
<div class="sect2">
<h3 id="_on_22_may_2015_154959_ann_campbell_wrote">on 22 May 2015, 15:49:59 Ann Campbell wrote:</h3>
<div class="paragraph">
<p>Thanks for this nearly-complete "stub", [~massimo.paladin].</p>
</div>
<div class="paragraph">
<p>Now I&#8217;m going to ask you to work some more :-)</p>
</div>
<div class="paragraph">
<p>Could you add a code snipped to illustrated the exception? I don&#8217;t quite understand it as-is, and I&#8217;m afraid others won&#8217;t either.</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_26_may_2015_122221_massimo_paladin_wrote">on 26 May 2015, 12:22:21 Massimo PALADIN wrote:</h3>
<div class="paragraph">
<p>\[~ann.campbell.2] I added a code snippet to the exceptions section, back to you for verification.</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_26_may_2015_140008_ann_campbell_wrote">on 26 May 2015, 14:00:08 Ann Campbell wrote:</h3>
<div class="paragraph">
<p>This looks great [~massimo.paladin], thanks!</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_29_may_2015_121220_dinesh_bolkensteyn_wrote">on 29 May 2015, 12:12:20 Dinesh Bolkensteyn wrote:</h3>
<div class="paragraph">
<p>\[~ann.campbell.2] I&#8217;m increasing the severity to CRITICAL with the agreement of [~mpaladin]: These issues must be fixed immediately - else you might ship broken code</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_29_may_2015_121521_ann_campbell_wrote">on 29 May 2015, 12:15:21 Ann Campbell wrote:</h3>
<div class="paragraph">
<p>Okay [~dinesh.bolkensteyn].</p>
</div>
</div>
<div class="sect2">
<h3 id="_on_19_mar_2019_162904_jeffrey_naisbitt_wrote">on 19 Mar 2019, 16:29:04 Jeffrey Naisbitt wrote:</h3>
<div class="paragraph">
<p>This rule appears to have a bug/false-positive when using AssertJ&#8217;s SoftAssertion feature.  AssertJ has a static method (SoftAssertions.assertSoftly) that calls assertAll() after its soft assertions.  Therefore, this case should not trigger the rule violation indicating 'assertAll' is needed:</p>
</div>
<div class="listingblock">
<div class="content">
<pre>import org.assertj.core.api.SoftAssertions;
import org.junit.Test;

public class Rule2970 {

  @Test
  public void test() {
    SoftAssertions.assertSoftly(softly -&gt; {
      softly.assertThat(true).isTrue();
      softly.assertThat(false).isFalse();
    });
  } // False-positive here: squid:S2970: "Add a call to 'assertAll' after all 'assertThat'."
}</pre>
</div>
</div>
</div>
</div>
</div>